# Generated by Django 4.2.6 on 2023-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('work', 'Work'), ('sport', 'Sport'), ('study', 'Study')], default='work', max_length=10),
        ),
    ]
