# Generated by Django 4.2.6 on 2023-11-25 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0003_todo_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('sport', 'Sport'), ('fun', 'Fun')], default='work', max_length=10),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
