# Generated by Django 4.2.6 on 2023-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_task_type_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('work', 'Work'), ('study', 'Study'), ('sport', 'Sport'), ('fun', 'Fun')], default='fun', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('study', 'Study'), ('work', 'Work'), ('sport', 'Sport'), ('fun', 'Fun')], max_length=10),
        ),
    ]
