# Generated by Django 4.2.6 on 2023-11-27 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_todo_priority_alter_todo_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
