# Generated by Django 4.2.6 on 2023-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Less', 'Low Priority')], default='Less', max_length=15),
        ),
    ]
