# Generated by Django 4.2.6 on 2023-12-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_alter_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
