# Generated by Django 4.2.6 on 2023-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0017_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_priority',
            field=models.CharField(choices=[('Élevé', 'élevé Priorité'), ('Moyen', 'moyen Priorité'), ('Faible', 'Faible Priorité')], default='Less', max_length=10),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_type',
            field=models.CharField(choices=[('études', 'Études'), ('travail', 'Travail'), ('sport', 'Sport'), ('loisirs', 'Loisirs')], max_length=10),
        ),
    ]
