# Generated by Django 4.2.6 on 2023-12-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0018_alter_todo_task_priority_alter_todo_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_priority',
            field=models.CharField(choices=[('Élevé', 'élevé Priorité'), ('Moyen', 'moyen Priorité'), ('Faible', 'Faible Priorité')], default='Faible', max_length=10),
        ),
    ]
